/* eslint-disable import/no-unresolved */
import { faker } from "@faker-js/faker";
import { PrismaClient } from "@prisma/client";
import slugify from "slugify";

import Bcrypt from "../src/utils/Bcrypt";

const prisma = new PrismaClient();

const main = async () => {
    await prisma.user.deleteMany({});
    await prisma.game.deleteMany({});
    await prisma.book.deleteMany({});
    await prisma.movie.deleteMany({});
    await prisma.tvshow.deleteMany({});
    await prisma.blog.deleteMany({});

    await prisma.user.createMany({
        data: [
            {
                email: "admin@gmail.com",
                name: "ADMIN",
                confirmed_email: true,
                confirm_email_token: null,
                password: await Bcrypt.hash("admin123"),
                reset_password_token: null,
                admin: true,
                phone: "16999999999",
                address_zipcode: null,
                address_street: null,
                address_street_number: null,
                address_neighborhood: null,
                address_city: null,
                address_state: null,
                address_country: null,
                stripe_customer_id: null,
                stripe_card_id: null,
                stripe_card_brand: null,
                stripe_card_last4: null,
                stripe_card_exp_month: null,
                stripe_card_exp_year: null,
                stripe_currently_subscription_id: null,
                stripe_currently_subscription_name: "FREE",
                stripe_subscription_start: null,
                stripe_subscription_end: null,
            },
            {
                email: "test@gmail.com",
                name: "User Test",
                confirmed_email: true,
                confirm_email_token: null,
                password: await Bcrypt.hash("test123"),
                reset_password_token: null,
                admin: false,
                phone: "16999999999",
                address_zipcode: "13560290",
                address_street: "Rua Dos Bobos",
                address_street_number: 42,
                address_neighborhood: "Bairro ",
                address_city: "São Paulo",
                address_state: "São Paulo",
                address_country: "Brazil",
                stripe_customer_id: null,
                stripe_card_id: null,
                stripe_card_brand: null,
                stripe_card_last4: null,
                stripe_card_exp_month: null,
                stripe_card_exp_year: null,
                stripe_currently_subscription_id: null,
                stripe_currently_subscription_name: "FREE",
                stripe_subscription_start: null,
                stripe_subscription_end: null,
            },
        ],
        skipDuplicates: true,
    });

    await prisma.blog.createMany({
        data: [
            {
                title: "Why Simpsons Is So Succesfull?",
                resume: "blog resume 1",
                image: faker.image.urlLoremFlickr(),
                category: "Software",
                slug: slugify("Why Simpsons Is So Succesfull?", {
                    lower: true,
                }),
                body: faker.lorem.paragraphs(),
            },
            {
                title: "Awesome Blog Post 2",
                resume: faker.lorem.text(),
                image: faker.image.urlLoremFlickr(),
                category: "Software",
                slug: slugify("Awesome Blog Post 2", { lower: true }),
                body: faker.lorem.paragraphs(),
            },
            {
                title: "Some Blog Post 3",
                resume: faker.lorem.text(),
                image: faker.image.urlLoremFlickr(),
                category: "Software",
                slug: slugify("Some Blog Post 3", { lower: true }),
                body: faker.lorem.paragraphs(),
            },
            {
                title: "Some Blog Post 4",
                resume: faker.lorem.text(),
                image: faker.image.urlLoremFlickr(),
                category: "Software",
                slug: slugify("Some Blog Post 4", { lower: true }),
                body: faker.lorem.paragraphs(),
            },
            {
                title: "Some Blog Post 5",
                resume: faker.lorem.text(),
                image: faker.image.urlLoremFlickr(),
                category: "Software",
                slug: slugify("Some Blog Post 5", { lower: true }),
                body: faker.lorem.paragraphs(),
            },
            {
                title: "Some Blog Post 6",
                resume: faker.lorem.text(),
                image: faker.image.urlLoremFlickr(),
                category: "Software",
                slug: slugify("Some Blog Post 6", { lower: true }),
                body: faker.lorem.paragraphs(),
            },
        ],
        skipDuplicates: true,
    });

    await prisma.game.createMany({
        data: [
            {
                title: "God of War Ragnarök",
                year_release: 2022,
                price: 6990,
                resume: `God of War: Ragnarök is the tentative title for the upcoming action-adventure game in development by Santa Monica Studio and to be published by Sony Interactive Entertainment (SIE). It is scheduled to be released in 2021 for the PlayStation 5 (PS5). It will be the ninth installment in the God of War series, the ninth chronologically, and the sequel to 2018's God of War. Loosely based on Norse mythology, the game will be set in ancient Norway and feature series protagonists Kratos, the former Greek God of War who remains the only playable character, and his young son Atreus. The game is expected to kick off the events of Ragnarök, a series of events that bring about the end of days and depict the deaths of the Norse gods in Norse mythology.`,
                image: `https://images.igdb.com/igdb/image/upload/t_cover_big/co3swk.png`,
                igdb_link: "https://www.igdb.com/games/god-of-war-ragnarok",
                igdb_rating: 95,
                platforms: "PS4, PS5",
                developer: "Santa Mônica Studios",
                genres: "Action, Third Person, Adventure, Hack and slash/Beat 'em up",
                amazon_link: "amazon_link_ragnarok",
            },
            {
                title: "God Of War",
                year_release: 2018,
                price: 2990,
                resume: `It is a new beginning for Kratos. Living as a man, outside the shadow of the gods, he seeks solitude in the unfamiliar lands of Norse mythology. With new purpose and his son at his side, Kratos must fight for survival as powerful forces threaten to disrupt the new life he has created...`,
                image: `https://images.igdb.com/igdb/image/upload/t_cover_big/co1tmu.jpg`,
                igdb_link: "https://www.igdb.com/games/god-of-war--1",
                igdb_rating: 95,
                platforms: "PS4, PS5",
                developer: "Santa Mônica Studios",
                genres: "Action, Third Person, Adventure, Hack and slash/Beat 'em up",
                amazon_link: "amazon_link_1",
            },
            {
                title: "Ghost Of Tsushima",
                year_release: 2020,
                price: 5990,
                resume: "The year is 1274. Samurai warriors are the legendary defenders of Japan — until the fearsome Mongol Empire invades the island of Tsushima, wreaking havoc and conquering the local population. As one of the last surviving samurai, you rise from the ashes to fight back. But, honorable tactics won’t lead you to victory. You must move beyond your samurai traditions to forge a new way of fighting — the way of the Ghost — as you wage an unconventional war for the freedom of Japan.",
                image: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2crj.jpg",
                igdb_link: "https://www.igdb.com/games/ghost-of-tsushima",
                igdb_rating: 90,
                platforms: "PS4, PS5",
                developer: "Sucker Punch Productions",
                genres: "Action, Third Person, Drama, Open world, Stealth, Adventure, Hack and slash/Beat 'em up",
                amazon_link: "amazon_link_2",
            },
            {
                title: "Marvel's SpiderMan",
                year_release: 2018,
                price: 3990,
                resume: "Starring the worlds most iconic Super Hero, Spider-Man features the acrobatic abilities, improvisation and web-slinging that the wall-crawler is famous for, while also introducing elements never-before-seen in a Spider-Man game. From traversing with parkour and utilizing the environment, to new combat and blockbuster set pieces, its Spider-Man unlike any you’ve played before.",
                image: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r77.jpg",
                igdb_link: "https://www.igdb.com/games/marvels-spider-man",
                igdb_rating: 88,
                platforms: "PS4, PS5",
                developer: "Insomniac Games",
                genres: "Action, Third Person, Drama, Open world, Stealth, Adventure, Hack and slash/Beat 'em up",
                amazon_link: "amazon_link_3",
            },
            {
                title: "Uncharted 4: A Thief's End",
                year_release: 2016,
                price: 1990,
                resume: "Several years after his last adventure, retired fortune hunter, Nathan Drake, is forced back into the world of thieves. With the stakes much more personal, Drake embarks on a globe-trotting journey in pursuit of a historical conspiracy behind a fabled pirate treasure. His greatest adventure will test his physical limits, his resolve, and ultimately what he's willing to sacrifice to save the ones he loves.",
                image: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r7h.jpg",
                igdb_link: "https://www.igdb.com/games/uncharted-4-a-thief-s-end",
                igdb_rating: 92,
                platforms: "PS4, PS5",
                developer: "Naughty Dog",
                genres: "SinglePlayer, Action, Drama, Stealth, Adventure",
                amazon_link: "amazon_link_4",
            },
            {
                title: "Uncharted: The Lost Legacy",
                year_release: 2017,
                price: 2990,
                resume: `From the critically acclaimed developer, Naughty Dog, comes the first standalone adventure in the Uncharted series. Fan-favorite character, Chloe Frazer, must enlist the aid of renowned mercenary Nadine Ross from Uncharted 4: A Thiefs End in order to recover a fabled ancient Indian artifact and keep it out of the hands of a ruthless war profiteer. Together, theyll venture deep into the mountains of India in search of the legendary artifact. Along the way, theyll learn to work together to unearth the mystery of the artifact, fight their way through fierce opposition, and prevent the region from falling into chaos.`,
                image: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1tp9.jpg",
                igdb_link: "https://www.igdb.com/games/uncharted-the-lost-legacy",
                igdb_rating: 92,
                platforms: "PS4, PS5",
                developer: "Naughty Dog",
                genres: "SinglePlayer, Third Person, Action, Drama, Stealth, Adventure",
                amazon_link: "amazon_link_5",
            },
            {
                title: "Bloodborne",
                year_release: 2015,
                price: 2990,
                resume: "An action RPG in which the player embodies a Hunter who, after being transfused with the mysterious blood local to the city of Yharnam, sets off into a 'night of the Hunt', an extended night in which Hunters may phase in and out of dream and reality in order to thin the outbreak of abominable beasts that plague the land and, for the more resilient and insightful Hunters, uncover the answers to the Hunt's many mysteries.",
                image: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rba.jpg",
                igdb_link: "https://www.igdb.com/games/bloodborne",
                igdb_rating: 91,
                platforms: "PS4, PS5",
                developer: "FromSoftware",
                genres: "SinglePlayer, Third Person, RPG, Action, Adventure",
                amazon_link: "amazon_link_6",
            },
            {
                title: "Persona 5 Royal",
                year_release: 2019,
                price: 3990,
                resume: "An enhanced version of Persona 5 with some new characters and a third semester added to the game. Released Internationally in 2020.",
                image: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1nic.jpg",
                igdb_link: "https://www.igdb.com/games/persona-5-royal",
                igdb_rating: 94,
                platforms: "PS4, PS5",
                developer: "Atlus",
                genres: "SinglePlayer, Third Person, RPG, Turn-Based, Adventure",
                amazon_link: "amazon_link_7",
            },
            {
                title: "God of War III",
                year_release: 2010,
                price: 990,
                resume: "Set in the realm of brutal Greek mythology, God of War III is a single-player game that allows players to take on the climatic role of the ex-Spartan warrior, Kratos, as he scales through the intimidating heights of Mt. Olympus and the dark depths of Hell to seek revenge on those who have betrayed him. Armed with double-chained blades, and an array of new weapons and magic for this iteration of the trilogy, Kratos must take on mythology's darkest creatures while solving intricate puzzles throughout his merciless quest to destroy Olympus.",
                image: "https://images.igdb.com/igdb/image/upload/t_cover_big/co30a3.jpg",
                igdb_link: "https://www.igdb.com/games/god-of-war-iii",
                igdb_rating: 86,
                platforms: "PS3, PS4",
                developer: "Santa Mônica Studios",
                genres: "SinglePlayer, Third Person, Adventure, Hack and slash/Beat 'em up",
                amazon_link: "amazon_link_god3",
            },
            {
                title: "The Last of Us Part II",
                year_release: 2020,
                price: 5990,
                resume: "Set 5 years after the events of The Last of Us, we see the return of Joel and Ellie. Driven by hatred, Ellie sets out for Seattle to serve justice. However, she begins to wonder what justice really means.",
                image: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r0o.jpg",
                igdb_link: "https://www.igdb.com/games/the-last-of-us-part-ii",
                igdb_rating: 93,
                platforms: "PS3, PS4",
                developer: "Naughty Dog",
                genres: "SinglePlayer, Third Person, Shooter, Adventure",
                amazon_link: "amazon_link_thelast",
            },
            {
                title: "The Last of Us",
                year_release: 2013,
                price: 2990,
                resume: "A third person shooter/stealth/survival hybrid, in which twenty years after the outbreak of a parasitic fungus which takes over the neural functions of humans, Joel, a Texan with a tragic familial past, finds himself responsible with smuggling a fourteen year old girl named Ellie to a militia group called the Fireflies, while avoiding strict and deadly authorities, infected fungal hosts and other violent survivors.",
                image: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r7f.jpg",
                igdb_link: "https://www.igdb.com/games/the-last-of-us",
                igdb_rating: 94,
                platforms: "PS3, PS4",
                developer: "Naughty Dog",
                genres: "SinglePlayer, Third Person, Shooter, Adventure",
                amazon_link: "amazon_link",
            },
            {
                title: "Hades",
                year_release: 2020,
                price: 2990,
                resume: "A rogue-lite hack and slash dungeon crawler in which Zagreus, son of Hades the Greek god of the dead, attempts to escape his home and his oppressive father by fighting the souls of the dead through the various layers of the ever-shifting underworld, while getting to know and forging relationships with its inhabitants.",
                image: "https://images.igdb.com/igdb/image/upload/t_cover_big/co39vc.jpg",
                igdb_link: "https://www.igdb.com/games/hades--1",
                igdb_rating: 94,
                platforms: "PC, XboxOne Series S|X, PS4, PS5",
                developer: "Supergiant Games",
                genres: "Adventure, Hack and slash/Beat 'em up, Indie, Role-playing (RPG)",
                amazon_link: "link da amazon",
            },
            {
                title: "Detroit: Become Human",
                year_release: 2018,
                price: 1990,
                resume: "Detroit: Become Human is an neo-noir thriller. The plot revolves around three androids: Kara, who escapes the factory she was made in to explore her newfound sentience; Connor, whose job it is to hunt down deviant androids like Kara; and Markus, who devotes himself to releasing the androids from servitude. The characters may survive or perish depending on the choices that are made, which serve to shape the story as customised by the player.",
                image: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2md2.png",
                igdb_link: "https://www.igdb.com/games/detroit-become-human--1",
                igdb_rating: 83,
                platforms: "PS4, PS5",
                developer: "Quantic Dream",
                genres: "Adventure, Puzzle",
                amazon_link: "mais umlink",
            },
            {
                title: "Shadow of the Colossus",
                year_release: 2018,
                price: 1990,
                resume: "Tales speak of an ancient land where creatures the size of mountains, roam the majestic landscape. Bound to the land, these creatures hold a key to a mystical power of revival - a power you must obtain to waken a loved one. Shadow of the Colossus is a majestic journey through ancient lands to seek out and destroy gigantic mythical beasts. With your trusty horse at your side, explore the spacious lands and unearth each Colossi. Armed with your wits, a sword and a bow, use cunning and strategy to topple each behemoth. A remake of the critically-claimed game of the same title. Also from the minds that brought you The Last Guardian & ICO",
                image: "https://images.igdb.com/igdb/image/upload/t_cover_big/co272w.png",
                igdb_link: "https://www.igdb.com/games/shadow-of-the-colossus--1",
                igdb_rating: 85,
                platforms: "PS4, PS5",
                developer: "Bluepoint Games",
                genres: "Single Player, Adventure, Platform",
                amazon_link: "algumlink",
            },
            {
                title: "Gran Turismo Sport",
                year_release: 2018,
                price: 1990,
                resume: "Welcome to the future of motorsports – the definitive motor racing experience is back and better than ever only on PlayStation 4. Gran Turismo Sport is the world’s first racing experience to be built from the ground up to bring global, online competitions sanctioned by the highest governing body of international motorsports, the FIA (Federation International Automobile). Create your legacy as you represent and compete for your home country or favorite manufacturer.",
                image: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1pd4.png",
                igdb_link: "https://www.igdb.com/games/gran-turismo-sport",
                igdb_rating: 76,
                platforms: "PS4, PS5",
                developer: "Bluepoint Games",
                genres: "Single/Multiplayer Player, Simulation, Race",
                amazon_link: "somelink",
            },
            {
                title: "Horizon Zero Dawn",
                year_release: 2018,
                price: 3990,
                resume: "Horizon Zero Dawn, an exhilarating new action role playing game exclusively for the PlayStation 4 system, developed by the award winning Guerrilla Games, creatos of PlayStation's venerated Killzone franchise. As Horizon Zero Dawn's main protagonist Aloy, a skilled hunter, explore a vibrant and lush world inhabited by mysterious mechanized creatures.",
                image: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2una.png",
                igdb_link: "https://www.igdb.com/games/horizon-zero-dawn",
                igdb_rating: 91,
                platforms: "PS4, PS5, PC",
                developer: "Guerrilla Games",
                genres: "Single Player, Adventure, Platform, Third Person",
                amazon_link: "herelink",
            },
            {
                title: "Final Fantasy 7 Remake",
                year_release: 2020,
                price: 5990,
                resume: "A spectacular re-imagining of one of the most visionary games ever, FINAL FANTASY VII REMAKE rebuilds and expands the legendary RPG for today. The first game in this project is set in the eclectic city of Midgar and presents a fully standalone gaming experience.",
                image: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1qxr.png",
                igdb_link: "https://www.igdb.com/games/final-fantasy-vii-remake",
                igdb_rating: 88,
                platforms: "PS4, PS5, PC",
                developer: "Square Enix",
                genres: "Single Player, Adventure, RPG, Third Person",
                amazon_link: "linkhere",
            },
            {
                title: "Death Stranding",
                year_release: 2019,
                price: 4990,
                resume: "Action & exploration third person game set in a post-apocalyptic open world.Developed by Kojima Productions and published first on PS4 by Sony Interactive and later on PC by 505 Games.",
                image: "https://images.igdb.com/igdb/image/upload/t_cover_big/co316v.png",
                igdb_link: "https://www.igdb.com/games/death-stranding",
                igdb_rating: 89,
                platforms: "PS4, PS5, PC",
                developer: "Kojima Productions",
                genres: "Single Player, Adventure, Third Person",
                amazon_link: "amazon_linkkk",
            },
            {
                title: "Metal Gear Solid V",
                year_release: 2015,
                price: 1990,
                resume: "The 5th installment of the Metal Gear Solid saga, Metal Gear Solid V: The Phantom Pain continues the story of Big Boss (aka Naked Snake, aka David), connecting the story lines from Metal Gear Solid: Peace Walker, Metal Gear Solid: Ground Zeroes, and the rest of the Metal Gear Universe.",
                image: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1v85.png",
                igdb_link: "https://www.igdb.com/games/metal-gear-solid-v-the-phantom-pain",
                igdb_rating: 86,
                platforms: "PS4, PS5, PC",
                developer: "Konami",
                genres: "Single Player, Adventure, Action, Shooter, Third Person",
                amazon_link: "amazon_link_here",
            },
            {
                title: "Uncharted: The Nathan Drake Collection",
                year_release: 2015,
                price: 5990,
                resume: "Uncharted: The Nathan Drake Collection is a remastered compilation of the action-adventure shooter platform video games Drake's Fortune, Among Thieves, and Drake's Deception. Ported by Bluepoint Games, the collection was released exclusively for the PlayStation 4 on October 7, 2015 in Europe and October 9th, 2015 in North America. The Nathan Drake Collection features the original three games in the Uncharted series with 1080p resolution, 60 frames per second, better lighting, textures and models. The collection also implements a photo mode, a mode where the player can freeze the game at any moment to take personalized screenshots, derived from Naughty Dog's other remastered entry, The Last of Us Remastered, as well as new trophies. The ported games only include their respective single-player modes.",
                image: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1tps.png",
                igdb_link: "https://www.igdb.com/games/uncharted-the-nathan-drake-collection",
                igdb_rating: 90,
                platforms: "PS4",
                developer: "Naughty Dog",
                genres: "Single Player, Adventure, Action, Shooter, Third Person",
                amazon_link: "amazon_link_heree",
            },
        ],
        skipDuplicates: false,
    });

    await prisma.book.createMany({
        data: [
            {
                title: "Sapiens: A Brief History of Humankind",
                year_release: 2014,
                price: 2990,
                image: "https://m.media-amazon.com/images/I/51Sn8PEXwcL.jpg",
                amazon_link:
                    "https://www.amazon.com/Sapiens-Humankind-Yuval-Noah-Harari-ebook/dp/B00ICN066A/ref=sr_1_2?crid=165V6E4JEUXKV&dchild=1&keywords=yuval+harari&qid=1632431375&s=digital-text&sprefix=yuval+ha%2Cdigital-text%2C288&sr=1-2",
                resume: "From a renowned historian comes a groundbreaking narrative of humanity’s creation and evolution—a #1 international bestseller—that explores the ways in which biology and history have defined us and enhanced our understanding of what it means to be “human.” One hundred thousand years ago, at least six different species of humans inhabited Earth. Yet today there is only one—homo sapiens. What happened to the others? And what may happen to us? Most books about the history of humanity pursue either a historical or a biological approach, but Dr. Yuval Noah Harari breaks the mold with this highly original book that begins about 70,000 years ago with the appearance of modern cognition. From examining the role evolving humans have played in the global ecosystem to charting the rise of empires, Sapiens integrates history and science to reconsider accepted narratives, connect past developments with contemporary concerns, and examine specific events within the context of larger ideas.",
                pages: 464,
                genres: "Historic",
                author: "Yuval Noah Harari ",
            },
            {
                title: "21 Lessons for the 21st Century",
                year_release: 2018,
                price: 2990,
                image: "https://m.media-amazon.com/images/I/41+uVWlucWL.jpg",
                amazon_link:
                    "https://www.amazon.com/Lessons-21st-Century-Yuval-Harari-ebook/dp/B079WM7KLS/ref=sr_1_1?crid=165V6E4JEUXKV&dchild=1&keywords=yuval+harari&qid=1632431324&s=digital-text&sprefix=yuval+ha%2Cdigital-text%2C288&sr=1-1",
                resume: "How do computers and robots change the meaning of being human? How do we deal with the epidemic of fake news? Are nations and religions still relevant? What should we teach our children? Yuval Noah Harari’s 21 Lessons for the 21st Century is a probing and visionary investigation into today’s most urgent issues as we move into the uncharted territory of the future. As technology advances faster than our understanding of it, hacking becomes a tactic of war, and the world feels more polarized than ever, Harari addresses the challenge of navigating life in the face of constant and disorienting change and raises the important questions we need to ask ourselves in order to survive.",
                pages: 355,
                genres: "Historic",
                author: "Yuval Harari",
            },
            {
                title: "Homo Deus: A Brief History of Tomorrow",
                year_release: 2016,
                price: 3990,
                image: "https://m.media-amazon.com/images/I/4193zapM4cL._SY346_.jpg",
                amazon_link: "https://www.amazon.com.br/gp/product/B01LXCJTO4/ref=dbs_a_def_rwt_bibl_vppi_i0",
                resume: "Yuval Noah Harari, author of the critically-acclaimed New York Times bestseller and international phenomenon Sapiens, returns with an equally original, compelling, and provocative book, turning his focus toward humanity’s future, and our quest to upgrade humans into gods. Over the past century humankind has managed to do the impossible and rein in famine, plague, and war. This may seem hard to accept, but, as Harari explains in his trademark style—thorough, yet riveting—famine, plague and war have been transformed from incomprehensible and uncontrollable forces of nature into manageable challenges. For the first time ever, more people die from eating too much than from eating too little; more people die from old age than from infectious diseases; and more people commit suicide than are killed by soldiers, terrorists and criminals put together. The average American is a thousand times more likely to die from binging at McDonalds than from being blown up by Al Qaeda.",
                pages: 464,
                genres: "Historic",
                author: "Yuval Noah Harari ",
            },
            {
                title: "The Code Breaker: Jennifer Doudna, Gene Editing, and the Future of the Human Race",
                year_release: 2020,
                price: 5990,
                image: "https://m.media-amazon.com/images/I/41sdqD62cSL._SY346_.jpg",
                amazon_link:
                    "https://www.amazon.com.br/dp/8532531768/ref=s9_acsd_al_bw_c2_x_1_t?pf_rd_m=A3RN7G7QC5MWSZ&pf_rd_s=merchandised-search-4&pf_rd_r=94401YP4EFQBKS2C6QK8&pf_rd_t=101&pf_rd_p=bed818b6-7184-4c08-8637-f6cb1f410f34&pf_rd_i=13348890011",
                resume: "The bestselling author of Leonardo da Vinci and Steve Jobs returns with a gripping account of how Nobel Prize winner Jennifer Doudna and her colleagues launched a revolution that will allow us to cure diseases, fend off viruses, and have healthier babies. When Jennifer Doudna was in sixth grade, she came home one day to find that her dad had left a paperback titled The Double Helix on her bed. She put it aside, thinking it was one of those detective tales she loved. When she read it on a rainy Saturday, she discovered she was right, in a way. As she sped through the pages, she became enthralled by the intense drama behind the competition to discover the code of life.",
                pages: 256,
                genres: "Biography",
                author: "Walter Isaacson",
            },
            {
                title: "Clean Code: A Handbook of Agile Software Craftsmanship",
                year_release: 2009,
                price: 1490,
                image: "https://images-na.ssl-images-amazon.com/images/I/41SH-SvWPxL._SX342_SY445_QL70_FMwebp_.jpg",
                amazon_link:
                    "https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship-ebook/dp/B001GSTOAM/ref=sr_1_1?crid=1AGS1CVBWJ2I9&dchild=1&keywords=clean+code&qid=1632431269&s=digital-text&sprefix=clean+code%2Cdigital-text%2C298&sr=1-1",
                resume: "Even bad code can function. But if code isn’t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn’t have to be that way. Noted software expert Robert C. Martin presents a revolutionary paradigm with Clean Code: A Handbook of Agile Software Craftsmanship. Martin has teamed up with his colleagues from Object Mentor to distill their best agile practice of cleaning code “on the fly” into a book that will instill within you the values of a software craftsman and make you a better programmer–but only if you work at it.",
                pages: 425,
                genres: "Software",
                author: "Robert C. Martin",
            },
            {
                title: "Domain-Driven Design: Tackling Complexity in the Heart of Software",
                year_release: 2016,
                price: 5990,
                image: "https://images-na.ssl-images-amazon.com/images/I/51OWGtzQLLL._SX342_SY445_QL70_FMwebp_.jpg",
                amazon_link:
                    "https://www.amazon.com/Domain-Driven-Design-Tackling-Complexity-Software-ebook/dp/B00794TAUG/ref=sr_1_1?crid=3MSX5CWJWV1HH&dchild=1&keywords=domain+driven+design&qid=1632431205&s=digital-text&sprefix=domain+dri%2Cdigital-text%2C295&sr=1-1",
                resume: "Domain-Driven Design fills that need. This is not a book about specific technologies. It offers readers a systematic approach to domain-driven design, presenting an extensive set of design best practices, experience-based techniques, and fundamental principles that facilitate the development of software projects facing complex domains. Intertwining design and development practice, this book incorporates numerous examples based on actual projects to illustrate the application of domain-driven design to real-world software development.",
                pages: 528,
                genres: "Software",
                author: "Eric Evans",
            },
            {
                title: "How To Win Friends and Influence People",
                year_release: 2012,
                price: 4390,
                image: "https://m.media-amazon.com/images/I/51NVtjOrnqL._SY346_.jpg",
                amazon_link:
                    "https://www.amazon.com/How-Win-Friends-Influence-People-ebook/dp/B003WEAI4E/ref=sr_1_1?crid=P2NW8U2G4S65&dchild=1&keywords=how+to+make+friends+and+influence+people&qid=1632431120&s=digital-text&sprefix=how+to+make+fri%2Cdigital-text%2C303&sr=1-1",
                resume: "Dale Carnegie’s rock-solid, time-tested advice has carried countless people up the ladder of success in their business and personal lives. One of the most groundbreaking and timeless bestsellers of all time, How to Win Friends & Influence People will teach you: -Six ways to make people like you -Twelve ways to win people to your way of thinking -Nine ways to change people without arousing resentment. And much more! Achieve your maximum potential—a must-read for the twenty-first century with more than 15 million copies sold!",
                pages: 254,
                genres: "Personal Development",
                author: "Dale Carnegie",
            },
            {
                title: "The Art Of War",
                year_release: 2021,
                price: 3490,
                image: "https://m.media-amazon.com/images/I/41MyeYYbBoL.jpg",
                amazon_link:
                    "https://www.amazon.com/Art-War-Sun-Tzu-ebook/dp/B003ZUY13E/ref=sr_1_1?crid=3716V7D9ETKYB&dchild=1&keywords=sun+tzu+art+of+war&qid=1632431049&s=digital-text&sprefix=sun+tzu%2Cdigital-text%2C289&sr=1-1",
                resume: "Art of War is almost certainly the most famous study of strategy ever written and has had an extraordinary influence on the history of warfare. The principles Sun-tzu expounded were utilized brilliantly by such great Asian war leaders as Mao Tse-tung, Giap, and Yamamoto. First translated two hundred years ago by a French missionary, Sun-tzu's Art of War has been credited with influencing Napoleon, the German General Staff, and even the planning for Desert Storm. Many Japanese companies make this book required reading for their key executives. And increasingly, Western businesspeople and others are turning to the Art of War for inspiration and advice on how to succeed in competitive situations of all kinds.",
                pages: 160,
                genres: "Strategic",
                author: "Sun Tzu",
            },
            {
                title: "Steve Jobs",
                year_release: 2020,
                price: 1990,
                image: "https://m.media-amazon.com/images/I/4119AW7yvlL.jpg",
                amazon_link: "https://www.amazon.com/gp/product/B004W2UBYW/ref=dbs_a_def_rwt_bibl_vppi_i1",
                resume: "Based on more than forty interviews with Steve Jobs conducted over two years—as well as interviews with more than 100 family members, friends, adversaries, competitors, and colleagues—Walter Isaacson has written a riveting story of the roller-coaster life and searingly intense personality of a creative entrepreneur whose passion for perfection and ferocious drive revolutionized six industries: personal computers, animated movies, music, phones, tablet computing, and digital publishing. Isaacson’s portrait touched millions of readers. At a time when America is seeking ways to sustain its innovative edge, Jobs stands as the ultimate icon of inventiveness and applied imagination. He knew that the best way to create value in the twenty-first century was to connect creativity with technology. He built a company where leaps of the imagination were combined with remarkable feats of engineering.",
                pages: 256,
                genres: "Biography",
                author: "Walter Isaacson",
            },
            {
                title: "Leonardo da Vinci",
                year_release: 2020,
                price: 5990,
                image: "https://m.media-amazon.com/images/I/51gFt86kFAL.jpg",
                amazon_link: "https://www.amazon.com/gp/product/B071Y385Q1/ref=dbs_a_def_rwt_bibl_vppi_i2",
                resume: "Based on thousands of pages from Leonardo da Vinci’s astonishing notebooks and new discoveries about his life and work, Walter Isaacson “deftly reveals an intimate Leonardo” (San Francisco Chronicle) in a narrative that connects his art to his science. He shows how Leonardo’s genius was based on skills we can improve in ourselves, such as passionate curiosity, careful observation, and an imagination so playful that it flirted with fantasy. He produced the two most famous paintings in history, The Last Supper and the Mona Lisa. With a passion that sometimes became obsessive, he pursued innovative studies of anatomy, fossils, birds, the heart, flying machines, botany, geology, and weaponry. He explored the math of optics, showed how light rays strike the cornea, and produced illusions of changing perspectives in The Last Supper. His ability to stand at the crossroads of the humanities and the sciences, made iconic by his drawing of Vitruvian Man, made him history’s most creative genius.",
                pages: 256,
                genres: "Biography",
                author: "Walter Isaacson",
            },
            {
                title: "Benjamin Franklin: An American Life",
                year_release: 2020,
                price: 4990,
                image: "https://images-na.ssl-images-amazon.com/images/I/51e4pdrIVKL._SX328_BO1,204,203,200_.jpg",
                amazon_link: "https://www.amazon.com/gp/product/B000FBJG4U/ref=dbs_a_def_rwt_bibl_vppi_i4",
                resume: "Benjamin Franklin is the founding father who winks at us, the one who seems made of flesh rather than marble. In a sweeping narrative that follows Franklin’s life from Boston to Philadelphia to London and Paris and back, Walter Isaacson chronicles the adventures of the runaway apprentice who became, over the course of his eighty-four-year life, America’s best writer, inventor, media baron, scientist, diplomat, and business strategist, as well as one of its most practical and ingenious political leaders. He explores the wit behind Poor Richard’s Almanac and the wisdom behind the Declaration of Independence, the new nation’s alliance with France, the treaty that ended the Revolution, and the compromises that created a near-perfect Constitution.",
                pages: 256,
                genres: "Biography",
                author: "Walter Isaacson",
            },
            {
                title: "Einstein: His Life and Universe",
                year_release: 2020,
                price: 3590,
                image: "https://m.media-amazon.com/images/I/510RQE9G+AL.jpg",
                amazon_link:
                    "https://www.amazon.com/Einstein-Life-Universe-Walter-Isaacson-ebook/dp/B000PC0S0K/ref=sr_1_1?crid=1SVNXRWCK9N0J&dchild=1&keywords=einstein&qid=1632431547&s=digital-text&sprefix=einstein%2Cdigital-text%2C306&sr=1-1",
                resume: "How did his mind work? What made him a genius? Isaacson’s biography shows how his scientific imagination sprang from the rebellious nature of his personality. His fascinating story is a testament to the connection between creativity and freedom. Based on newly released personal letters of Einstein, this book explores how an imaginative, impertinent patent clerk—a struggling father in a difficult marriage who couldn’t get a teaching job or a doctorate—became the mind reader of the creator of the cosmos, the locksmith of the mysteries of the atom, and the universe. His success came from questioning conventional wisdom and marveling at mysteries that struck others as mundane. This led him to embrace a morality and politics based on respect for free minds, free spirits, and free individuals. These traits are just as vital for this new century of globalization, in which our success will depend on our creativity, as they were for the beginning of the last century, when Einstein helped usher in the modern age.",
                pages: 705,
                genres: "Biography",
                author: "Walter Isaacson",
            },
            {
                title: "Elon Musk: Tesla, SpaceX, and the Quest for a Fantastic Future",
                year_release: 2015,
                price: 2790,
                image: "https://m.media-amazon.com/images/I/51tw6UjHpDL._SY346_.jpg",
                amazon_link:
                    "https://www.amazon.com/Elon-Musk-SpaceX-Fantastic-Future-ebook/dp/B00KVI76ZS/ref=sr_1_1?crid=1L76QFVRLPXOW&dchild=1&keywords=elon+musk&qid=1632431662&s=digital-text&sprefix=elon+musk%2Cdigital-text%2C303&sr=1-1",
                resume: "In Elon Musk: Tesla, SpaceX, and the Quest for a Fantastic Future, veteran technology journalist Ashlee Vance provides the first inside look into the extraordinary life and times of Silicon Valley's most audacious entrepreneur. Written with exclusive access to Musk, his family and friends, the book traces the entrepreneur's journey from a rough upbringing in South Africa to the pinnacle of the global business world. Vance spent over 40 hours in conversation with Musk and interviewed close to 300 people to tell the tumultuous stories of Musk's world-changing companies: PayPal, Tesla Motors, SpaceX and SolarCity, and to characterize a man who has renewed American industry and sparked new levels of innovation while making plenty of enemies along the way.",
                pages: 705,
                genres: "Biography",
                author: "Walter Isaacson",
            },
            {
                title: "Alice's Adventures in Wonderland",
                year_release: 1865,
                price: 2490,
                image: "https://m.media-amazon.com/images/I/51HFDCO5f4L.jpg",
                amazon_link:
                    "https://www.amazon.com/Alices-Adventures-Wonderland-Lewis-Carroll-ebook/dp/B09DJNGYJZ/ref=sr_1_2?crid=1U7MZJ195HFXT&dchild=1&keywords=alice+in+wonderland&qid=1632431725&s=digital-text&sprefix=alice+in%2Cdigital-text%2C309&sr=1-2",
                resume: "In Alice in Wonderland looking for a pastime, Alice will discover a whole new world and its bizarre inhabitants. In Through the Looking-Glass, six months after the visit to Wonderland, crossing a mirror, Alice is once again involved in unlikely adventures.",
                pages: 95,
                genres: "Fantasy, Fiction",
                author: "Lewis Carroll",
            },
            {
                title: "The Lean Startup: How Today's Entrepreneurs Use Continuous Innovation to Create Radically Successful Businesses",
                year_release: 2011,
                price: 3190,
                image: "https://m.media-amazon.com/images/I/51N-u8AsmdL.jpg",
                amazon_link:
                    "https://www.amazon.com/Lean-Startup-Entrepreneurs-Continuous-Innovation-ebook/dp/B004J4XGN6/ref=sr_1_1?crid=1F9VTKTRXNCT7&dchild=1&keywords=lean+startup&qid=1632431932&s=digital-text&sprefix=lean+st%2Cdigital-text%2C302&sr=1-1",
                resume: "Most startups fail. But many of those failures are preventable. The Lean Startup is a new approach being adopted across the globe, changing the way companies are built and new products are launched. Eric Ries defines a startup as an organization dedicated to creating something new under conditions of extreme uncertainty. This is just as true for one person in a garage or a group of seasoned professionals in a Fortune 500 boardroom. What they have in common is a mission to penetrate that fog of uncertainty to discover a successful path to a sustainable business. The Lean Startup approach fosters companies that are both more capital efficient and that leverage human creativity more effectively. Inspired by lessons from lean manufacturing, it relies on “validated learning,” rapid scientific experimentation, as well as a number of counter-intuitive practices that shorten product development cycles, measure actual progress without resorting to vanity metrics, and learn what customers really want. It enables a company to shift directions with agility, altering plans inch by inch, minute by minute.",
                pages: 92,
                genres: "Bussiness",
                author: "Eric Reis",
            },
            {
                title: "I, Robot",
                year_release: 1982,
                price: 1990,
                image: "https://m.media-amazon.com/images/I/41ED86iNFkL.jpg",
                amazon_link:
                    "https://www.amazon.com/I-Robot-Book-1-ebook/dp/B000FC1PW0/ref=sr_1_2?crid=37Q92VPCQTPHH&dchild=1&keywords=isaac+asimov&qid=1632432064&s=digital-text&sprefix=isaac+asi%2Cdigital-text%2C305&sr=1-2",
                resume: "I, Robot, the first and most widely read book in Asimov’s Robot series, forever changed the world’s perception of artificial intelligence. Here are stories of robots gone mad, of mind-reading robots, and robots with a sense of humor. Of robot politicians, and robots who secretly run the world—all told with the dramatic blend of science fact and science fiction that has become Asimov’s trademark. The Three Laws of Robotics: 1) A robot may not injure a human being or, through inaction, allow a human being to come to harm. 2) A robot must obey orders given to it by human beings except where such orders would conflict with the First Law. 3) A robot must protect its own existence as long as such protection does not conflict with the First or Second Law.",
                pages: 92,
                genres: "Science Fiction",
                author: "Isaac Asimov",
            },
            {
                title: "The Hitchhiker's Guide to the Galaxy",
                year_release: 2007,
                price: 990,
                image: "https://m.media-amazon.com/images/I/51vfuNNWMTS.jpg",
                amazon_link:
                    "https://www.amazon.com/Hitchhikers-Guide-Galaxy-Douglas-Adams-ebook/dp/B000XUBC2C/ref=sr_1_1?dchild=1&keywords=The+Hitchhiker%27s+Guide+to+the+Galaxy&qid=1632432113&s=digital-text&sr=1-1",
                resume: "It’s an ordinary Thursday morning for Arthur Dent . . . until his house gets demolished. The Earth follows shortly after to make way for a new hyperspace express route, and Arthur’s best friend has just announced that he’s an alien. After that, things get much, much worse. With just a towel, a small yellow fish, and a book, Arthur has to navigate through a very hostile universe in the company of a gang of unreliable aliens. Luckily the fish is quite good at languages. And the book is The Hitchhiker’s Guide to the Galaxy . . . which helpfully has the words DON’T PANIC inscribed in large, friendly letters on its cover. Douglas Adams’s mega-selling pop-culture classic sends logic into orbit, plays havoc with both time and physics, offers up pithy commentary on such things as ballpoint pens, potted plants, and digital watches . . . and, most important, reveals the ultimate answer to life, the universe, and everything.",
                pages: 103,
                genres: "Science Fiction",
                author: "Douglas Adams",
            },
            {
                title: "Foundation",
                year_release: 2007,
                price: 2990,
                image: "https://m.media-amazon.com/images/I/41sIWKtP-4L.jpg",
                amazon_link:
                    "https://www.amazon.com/Foundation-Isaac-Asimov-ebook/dp/B000FC1PWA/ref=sr_1_1?crid=20BD250HGCU0S&dchild=1&keywords=foundation+asimov&qid=1632432306&s=digital-text&sprefix=foundation%2Cdigital-text%2C320&sr=1-1",
                resume: "For twelve thousand years the Galactic Empire has ruled supreme. Now it is dying. But only Hari Seldon, creator of the revolutionary science of psychohistory, can see into the future—to a dark age of ignorance, barbarism, and warfare that will last thirty thousand years. To preserve knowledge and save humankind, Seldon gathers the best minds in the Empire—both scientists and scholars—and brings them to a bleak planet at the edge of the galaxy to serve as a beacon of hope for future generations. He calls his sanctuary the Foundation. The Foundation novels of Isaac Asimov are among the most influential in the history of science fiction, celebrated for their unique blend of breathtaking action, daring ideas, and extensive worldbuilding. In Foundation, Asimov has written a timely and timeless novel of the best—and worst—that lies in humanity, and the power of even a few courageous souls to shine a light in a universe of darkness.",
                pages: 255,
                genres: "Science Fiction",
                author: "Isaac Asimov",
            },
        ],
        skipDuplicates: true,
    });

    await prisma.movie.createMany({
        data: [
            {
                title: "Duna",
                year_release: 2021,
                image: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
                tmdb_link: "https://www.themoviedb.org/movie/438631-dune?language=en-US",
                tmdb_rating: 79,
                justwatch_link: null,
                resume: `Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence - a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.`,
                genres: "Action, Adventure",
                duration: "2h 15min",
            },
            {
                title: "Spider-Man: No Way Home",
                year_release: 2021,
                image: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
                tmdb_link: "https://www.themoviedb.org/movie/634649-spider-man-no-way-home?language=en-US",
                tmdb_rating: 95,
                justwatch_link: null,
                resume: "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
                genres: "Action, Adventure",
                duration: "2h 28min",
            },
            {
                title: "Shang-Chi and the Legend of the Ten Rings",
                year_release: 2021,
                image: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg",
                tmdb_link:
                    "https://www.themoviedb.org/movie/566525-shang-chi-and-the-legend-of-the-ten-rings?language=en-US",
                tmdb_rating: 78,
                justwatch_link: null,
                resume: "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
                genres: "Action, Adventure",
                duration: "2h 12min",
            },
            {
                title: "Encanto",
                year_release: 2021,
                image: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
                tmdb_link: "https://www.themoviedb.org/movie/568124-encanto?language=en-US",
                tmdb_rating: 82,
                justwatch_link: null,
                resume: `The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family with a unique gift from super strength to the power to heal—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional family's last hope.`,
                genres: "Action, Adventure",
                duration: "1h 42min",
            },
            {
                title: "The Matrix Resurrections ",
                year_release: 2021,
                image: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/8c4a8kE7PizaGQQnditMmI1xbRp.jpg",
                tmdb_link: "https://www.themoviedb.org/movie/624860-the-matrix-resurrections?language=en-US",
                tmdb_rating: 75,
                justwatch_link: null,
                resume: `Plagued by strange memories, Neo's life takes an unexpected turn when he finds himself back inside the Matrix.`,
                genres: "Action, Adventure",
                duration: "2h 28min",
            },
            {
                title: "The Last Duel",
                year_release: 2021,
                image: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/zjrJE0fpzPvX8saJXj8VNfcjBoU.jpg",
                tmdb_link: "https://www.themoviedb.org/movie/617653-the-last-duel?language=en-US",
                tmdb_rating: 81,
                justwatch_link: null,
                resume: `King Charles VI declares that Knight Jean de Carrouges settle his dispute with his squire, Jacques Le Gris, by challenging him to a duel.`,
                genres: "Action, Adventure",
                duration: "2h 32min",
            },
            {
                title: "Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train",
                year_release: 2020,
                image: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg",
                tmdb_link: "https://www.themoviedb.org/movie/635302?language=en-US",
                tmdb_rating: 84,
                justwatch_link: null,
                resume: `Tanjirō Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyōjurō Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!`,
                genres: "Action, Adventure",
                duration: "1h 57min",
            },
            {
                title: "Spider-Man: Into the Spider-Verse",
                year_release: 2020,
                image: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
                tmdb_link: "https://www.themoviedb.org/movie/324857-spider-man-into-the-spider-verse?language=en-US",
                tmdb_rating: 84,
                justwatch_link: null,
                resume: `Miles Morales is juggling his life between being a high school student and being a spider-man. When Wilson "Kingpin" Fisk uses a super collider, others from across the Spider-Verse are transported to this dimension.`,
                genres: "Action, Adventure",
                duration: "1h 57min",
            },
        ],
        skipDuplicates: true,
    });

    await prisma.tvshow.createMany({
        data: [
            {
                title: "The Witcher",
                year_release: 2021,
                image: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/7vjaCdMw15FEbXyLQTVa04URsPm.jpg",
                tmdb_link: "https://www.themoviedb.org/tv/71912-the-witcher?language=en-US",
                tmdb_rating: 87,
                justwatch_link: null,
                resume: "Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.",
                genres: "Action, Adventure",
                duration: "50min-1h",
            },
            {
                title: "The Wheel Of Time",
                year_release: 2021,
                image: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/mpgDeLhl8HbhI03XLB7iKO6M6JE.jpg",
                tmdb_link: "https://www.themoviedb.org/tv/71914-the-wheel-of-time?language=en-US",
                tmdb_rating: 83,
                justwatch_link: null,
                resume: "Follow Moiraine, a member of the shadowy and influential all-female organization called the “Aes Sedai” as she embarks on a dangerous, world-spanning journey with five young men and women. Moiraine believes one of them might be the reincarnation of an incredibly powerful individual, whom prophecies say will either save humanity or destroy it.",
                genres: "Action, Adventure",
                duration: "50-60min",
            },
            {
                title: "Money Heist",
                year_release: 2017,
                image: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
                tmdb_link: "https://www.themoviedb.org/tv/71446-la-casa-de-papel?language=en-US",
                tmdb_rating: 95,
                justwatch_link: null,
                resume: "To carry out the biggest heist in history, a mysterious man called The Professor recruits a band of eight robbers who have a single characteristic: none of them has anything to lose. Five months of seclusion - memorizing every step, every detail, every probability - culminate in eleven days locked up in the National Coinage and Stamp Factory of Spain, surrounded by police forces and with dozens of hostages in their power, to find out whether their suicide wager will lead to everything or nothing.",
                genres: "Action, Adventure",
                duration: "40-60min",
            },
            {
                title: "Squid Game",
                year_release: 2021,
                image: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
                tmdb_link: "https://www.themoviedb.org/tv/93405?language=en-US",
                tmdb_rating: 95,
                justwatch_link: null,
                resume: `Hundreds of cash-strapped players accept a strange invitation to compete in children's games—with high stakes.But, a tempting prize awaits the victor.`,
                genres: "Action, Adventure",
                duration: "50-60min",
            },
            {
                title: "Arcane",
                year_release: 2021,
                image: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
                tmdb_link: "https://www.themoviedb.org/tv/94605-arcane?language=en-US",
                tmdb_rating: 92,
                justwatch_link: null,
                resume: `Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.`,
                genres: "Action, Adventure",
                duration: "35-45min",
            },
            {
                title: "Arcane",
                year_release: 2021,
                image: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/w21lgYIi9GeUH5dO8l3B9ARZbCB.jpg",
                tmdb_link: "https://www.themoviedb.org/tv/1402-the-walking-dead?language=en-US",
                tmdb_rating: 92,
                justwatch_link: null,
                resume: `Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.`,
                genres: "Action, Adventure",
                duration: "35-45min",
            },
            {
                title: "Game of Thrones",
                year_release: 2011,
                image: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
                tmdb_link: "https://www.themoviedb.org/tv/1399-game-of-thrones?language=en-US",
                tmdb_rating: 87,
                justwatch_link: null,
                resume: `Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.`,
                genres: "Action, Adventure",
                duration: "50-60min",
            },
            {
                title: "Rick and Morty",
                year_release: 2013,
                image: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/8kOWDBK6XlPUzckuHDo3wwVRFwt.jpg",
                tmdb_link: "https://www.themoviedb.org/tv/60625-rick-and-morty?language=en-US",
                tmdb_rating: 88,
                justwatch_link: null,
                resume: `Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.`,
                genres: "Action, Adventure",
                duration: "20-25min",
            },
        ],
        skipDuplicates: true,
    });
};

main();
